account/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path('signup/', views.account_signup, name="signup"),
    path('login/', views.account_login, name="login"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
]

pizarra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('account/', include("account.urls")),
    path('projects/', include("projects.urls")),
]

projects/urls.py
from django.urls import path, include
from . import views

app_name = "projects"


urlpatterns = [
    path('', views.home, name="projects"),
    path('new/', views.new_project, name="new_project"),
    path('<uuid:pk>/', views.details, name="details"),
    path('<uuid:pk>/edit/', views.edit, name="edit"),
    path('<uuid:pk>/delete/', views.delete, name="delete"),
    path('<uuid:proj_id>/tasks/', include("tasks.urls")),
    path('<uuid:proj_id>/notes/', include("notes.urls")),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def home(req):
    return render(req, "core/home.html")


def about(req):
    return render(req, "core/about.html")

core/templates/core/about.html
{% extends "core/base.html" %}

{% block main %}
    <h1 class="text-3xl">About Pizarra</h1>
    <div class="mt-6 space-y-6">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque dolor iusto magnam, rerum consequatur quia obcaecati nemo, aspernatur, debitis consequuntur sit dignissimos molestiae harum autem labore illum tempora consectetur rem?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque dolor iusto magnam, rerum consequatur quia obcaecati nemo, aspernatur, debitis consequuntur sit dignissimos molestiae harum autem labore illum tempora consectetur rem?</p>
    </div>

{% endblock main %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizarra</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.6.0/css/all.min.css" integrity="sha512-ykRBEJhyZ+B/BIJcBuOyUoIxh0OfdICfHPnPfBy7eIiyJv536ojTCsgX8aqrLQ9VJZHGz4tvYyzOM0lkgmQZGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
        <a href="{% url "core:home" %}"><h1 class="text-xl text-white">Pizarra</h1></a>
        <div class="space-x-4">
            <a href="{% url "core:about" %}" class="text-white">About</a>
        {% if request.user.is_authenticated %}
            <a href="{% url "projects:projects" %}" class="py-4 px-8 bg-slate-600 text-white">My Projects</a>
            <a href="#" class="py-4 px-8 bg-sky-600 text-white">My Account</a>       
        {% else %}
            <a href="{% url "account:login" %}" class="py-4 px-8 bg-slate-600 text-white">Log in</a>
            <a href="{% url "account:signup" %}" class="py-4 px-8 bg-sky-600 text-white">Sign up</a>
        {% endif %}
        </div>
    </nav>

    <main class="py-8 px-8">
        {% block main %}
        {% endblock main %}
    </main>

    <footer class="py-8 px-8 bg-slate-800 text-center">
        <p class="text-white">Copyright &copy; 2024 - Unkerpaulie</p>
        <p><a href="/admin">Admin log in</a></p>
    </footer>
</body>
</html>

core/templates/core/home.html
{% extends "core/base.html" %}

{% block main %}
<header class="py-12 text-center bg-slate-200">
    <h1 class="text-3xl">Welcome to Pizarra</h1>
</header>
{% endblock main %}