core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
]

pizarra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('account/', include("account.urls")),
    path('projects/', include("projects.urls")),
]

projects/urls.py
from django.urls import path, include
from . import views

app_name = "projects"


urlpatterns = [
    path('', views.home, name="projects"),
    path('new/', views.new_project, name="new_project"),
    path('<uuid:pk>/', views.details, name="details"),
    path('<uuid:pk>/edit/', views.edit, name="edit"),
    path('<uuid:pk>/delete/', views.delete, name="delete"),
    path('<uuid:proj_id>/tasks/', include("tasks.urls")),
    path('<uuid:proj_id>/notes/', include("notes.urls")),
]

projects/models.py
import uuid
from django.db import models
from account.models import User


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="projects", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Project

# only accessible if logged in
@login_required
def home(req):
    project_list = Project.objects.filter(created_by=req.user)
    context = {"projects": project_list}
    return render(req, "projects/home.html", context)

@login_required
def new_project(req):
    if req.method == "POST":
        name = req.POST.get("name", "")
        description = req.POST.get("description", "")

        if name:
            Project.objects.create(name=name, description=description, created_by=req.user)
            # project.save()
            return redirect("/projects")

    return render(req, "projects/new.html")

@login_required
def details(req, pk):
    project = Project.objects.filter(created_by=req.user).get(pk=pk)
    tasks = project.tasks.all()
    note_count= project.notes.count()
    context = {"project": project, "tasks": tasks, "note_count": note_count}

    return render(req, "projects/detail.html", context)


@login_required
def edit(req, pk):
    project = Project.objects.filter(created_by=req.user).get(pk=pk)

    if req.method == "POST":
        name = req.POST.get("name", "")
        description = req.POST.get("description", "")

        if name:
            project.name = name
            project.description = description
            project.save()
            return redirect(f"/projects/{pk}")
    context = {"project": project}

    return render(req, "projects/edit.html", context)
 
@login_required
def delete(req, pk):
    if req.method == "POST":
        project = Project.objects.filter(created_by=req.user).get(pk=pk)
        project.delete()

        return redirect("/projects")

projects/templates/projects/detail.html
{% extends "core/base.html" %}

{% block main %}
    <div class="px-6 py-6 bg-slate-300">
        <h1 class="text-3xl mb-4">{{ project.name }}</h1>
        <a href="#" class="py-2 px-4 bg-emerald-600 text-white inine-block">Mark as done</a>
        <a href="{% url "projects:edit" project.id  %}" class="py-2 px-4 bg-sky-600 text-white inine-block">Edit</a>
        <button type="button" class="py-2 px-4 bg-amber-600 text-white inine-block">Delete</button>
        <p class="text-sm text-slate-600 my-4">{{ project.description }}</p>
        
        <!-- tasks -->
        <hr class="my-4 border-slate-800">
        <a href="{% url "projects:tasks:new_task" project.id %}" class="py-2 px-4 bg-sky-800 text-white inline-block">Add task</a>
        <a href="{% url "projects:notes:home" project.id %}" class="py-2 px-4 bg-lime-800 text-white inline-block">View project notes 	&#40;{{ note_count }}&#41;</a>
        <div class="mt-6 grid grid-cols-4 gap-4">

            {% for task in tasks %}
            <div class="px-6 py-6 bg-slate-200">
                <h2 class="mb-4 text-xl">{{ task.name }}</h2>
                <p class="text-sm text-slate-600 mb-4">{{ task.description }}</p>
                {% if task.due_date %}
                <p class="text-sm text-slate-600 mb-4">Due Date: {{ task.due_date|date:"D d M Y" }}</p>
                {% endif %}
                <div class="flex flex-row justify-between">
                    <button class="text-center text-sky-600 bg-gray-100 py-2 px-4 rounded hover:bg-gray-200 border border-gray-300" title="Edit" onclick="openModal('editTaskModal{{ forloop.counter }}')"><i class="fas fa-edit"></i></button>
                    <button class="text-center text-amber-600 bg-gray-100 py-2 px-4 rounded hover:bg-gray-200 border border-gray-300" title="Delete" onclick="openModal('deleteTaskModal{{ forloop.counter }}')"><i class="fas fa-trash-alt"></i></button>
                    <form action="{% url "projects:tasks:done" project.id task.id %}" method="post">
                        {% csrf_token %}
                        <button class="text-center bg-gray-100 py-2 px-4 rounded hover:bg-gray-200 border border-gray-300 {% if task.done %}text-emerald-600{% else%}text-gray-400{% endif %}" 
                        title="{% if task.done %}Completed{% else%}Mark as done{% endif %}"><i class="fas fa-check"></i></button>
                    </form>
                    <button class="text-center text-rose-600 bg-gray-100 py-2 px-4 rounded hover:bg-gray-200 border border-gray-300" title="Add Reminder"><i class="fas fa-bell"></i></button>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>

    <!-- Delete Project Modal -->
    <div id="deleteProjectModal" class="fixed hidden z-50 inset-0 bg-gray-900 bg-opacity-60 overflow-y-auto h-full w-full px-4 ">
        <div class="relative top-40 mx-auto shadow-xl rounded-md bg-white max-w-md">
            <div class="flex justify-end p-2">
                <button onclick="closeModal('deleteProjectModal')" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"><i class="fas fa-times"></i></button>
            </div>
            <div class="p-6 pt-0 text-center">
                <h3 class="text-xl font-normal text-gray-700 mt-5 mb-6">{{ project.name }}</h3>
                <p class="text-gray-500 mb-4">This project and all its related tasks will be deleted.</p>
                <div class="flex flex-row justify-around">
                    <form action="{% url "projects:delete" project.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                            Confirm
                        </button>
                    </form>
                    <a href="#" onclick="closeModal('deleteProjectModal')"
                        class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                        Cancel
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Task modals-->
    {% for task in tasks %}
    <div id="editTaskModal{{ forloop.counter }}" class="fixed hidden z-50 inset-0 bg-gray-900 bg-opacity-60 overflow-y-auto h-full w-full px-4 ">
        <div class="relative top-10 max-w-xl mx-auto py-8 bg-slate-800 text-center">
            <div class="flex justify-end p-2">
                <button onclick="closeModal('editTaskModal{{ forloop.counter }}')" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"><i class="fas fa-times"></i></button>
            </div>
            <h2 class="text-xl text-white">Edit Task</h2>
            <form action="{% url "projects:tasks:edit" project.id task.id %}" method="post" class="mt-6 px-8 space-y-4">
                {% csrf_token %}
                <div>
                    <label for="name" class="text-white">Task Name</label>
                    <input type="text" value="{{ task.name }}" name="name" class="w-full py-4 px-6 bg-slate-500 text-white">
                </div>
                <div>
                    <label for="description" class="text-white">Description</label>
                    <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ task.description }}</textarea>
                </div>
                <div>
                    <label for="due_date" class="text-white">Due Date</label>
                    <input type="date" name="due_date" class="w-full py-4 px-6 bg-slate-500 text-white">
                </div>
                <div>
                    <button type="submit" class="py-4 px-8 bg-sky-600 text-white">Edit task</button>
                </div>
            </form>
            </div>
        </div>
    </div>
    {% endfor %}
    

    <!-- Delete Task modals-->
    {% for task in tasks %}
    <div id="deleteTaskModal{{ forloop.counter }}" class="fixed hidden z-50 inset-0 bg-gray-900 bg-opacity-60 overflow-y-auto h-full w-full px-4 ">
        <div class="relative top-40 mx-auto shadow-xl rounded-md bg-white max-w-md">
            <div class="flex justify-end p-2">
                <button onclick="closeModal('deleteTaskModal{{ forloop.counter }}')" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"><i class="fas fa-times"></i></button>
            </div>
            <div class="p-6 pt-0 text-center">
                <h3 class="text-xl font-normal text-gray-700 mt-5 mb-6">{{ task.name }}</h3>
                <p class="text-gray-500 mb-4">Delete this task?</p>
                <div class="flex flex-row justify-around">
                    <form action="{% url "projects:tasks:delete" project.id task.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                            Confirm
                        </button>
                    </form>
                    <a href="#" onclick="closeModal('deleteTaskModal{{ forloop.counter }}')"
                        class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                        Cancel
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}



    

<script type="text/javascript">
    window.openModal = function(modalId) {
        document.getElementById(modalId).style.display = 'block'
        document.getElementsByTagName('body')[0].classList.add('overflow-y-hidden')
    }

    window.closeModal = function(modalId) {
        document.getElementById(modalId).style.display = 'none'
        document.getElementsByTagName('body')[0].classList.remove('overflow-y-hidden')
    }

    // Close all modals when press ESC
    document.onkeydown = function(event) {
        event = event || window.event;
        if (event.keyCode === 27) {
            document.getElementsByTagName('body')[0].classList.remove('overflow-y-hidden')
            let modals = document.getElementsByClassName('modal');
            Array.prototype.slice.call(modals).forEach(i => {
                i.style.display = 'none'
            })
        }
    };
</script>
{% endblock main %}

projects/templates/projects/edit.html
{% extends "core/base.html" %}

{% block main %}
<div class="max-w-xl mx-auto py-8 bg-slate-800 text-center">
    <h1 class="text-3xl text-white">Edit project</h1>
    <form action="" method="post" class="mt-6 px-8 space-y-4">
        {% csrf_token %}
        <div>
            <label for="name" class="text-white">Project Name</label>
            <input type="text" name="name" value="{{ project.name }}" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>
        <div>
            <label for="description" class="text-white">Description</label>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ project.description }}</textarea>
        </div>
        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Edit project</button>
        </div>
    </form>
</div>
{% endblock main %}

projects/templates/projects/home.html
{% extends "core/base.html" %}

{% block main %}
    <h1 class="text-3xl mb-4">Projects</h1>

    <a href="{% url "projects:new_project" %}" class="py-2 px-4 bg-sky-800 text-white inline-block">New project</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for project in projects %}
        <div class="px-6 py-6 bg-slate-200">
            <a href="{% url "projects:details" project.id %}"><h2 class="mb-4 text-xl hover:underline">{{ project.name }}</h2></a>
            <p class="text-sm text-slate-600 mb-4">{{ project.description }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock main %}

projects/templates/projects/new.html
{% extends "core/base.html" %}

{% block main %}
<div class="max-w-xl mx-auto py-8 bg-slate-800 text-center">
    <h1 class="text-3xl text-white">Create project</h1>
    <form action="" method="post" class="mt-6 px-8 space-y-4">
        {% csrf_token %}
        <div>
            <label for="name" class="text-white">Project Name</label>
            <input type="text" name="name" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>
        <div>
            <label for="description" class="text-white">Description</label>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>
        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Create project</button>
        </div>
    </form>
</div>
{% endblock main %}